import Link from "next/link";
import { whatsappHref } from "./site-content";
import { FloatingWhatsApp } from "./components/FloatingWhatsApp";
import { SiteFooter } from "./components/SiteFooter";
import { SiteHeader } from "./components/SiteHeader";
import { WhatsAppIcon } from "./components/WhatsAppIcon";

const collections = [
  { title: "Hoş Geldin Bebek", text: "Yeni bir başlangıcın mutluluğunu zarif çiçekler ve sevimli detaylarla kutlayın.", image: "/luniva/blue-swan-room-clean.png", href: "/hosgeldin-bebek-aranjmanlari" },
  { title: "İsme Özel Tasarımlar", text: "Bebeğinizin ismiyle kişiselleştirilen, hatırası uzun süre kalan hediyeler.", image: "/luniva/purple-swan-room-clean.png", href: "/isme-ozel-bebek-kapi-susleri" },
  { title: "Çiçekli Hediye Kutuları", text: "En özel günleriniz için özenle bir araya getirilen yumuşak tonlu sunumlar.", image: "/luniva/family-gift.png", href: "/cicekli-bebek-hediyeleri" },
];
export default function Home() { return <main className="min-h-screen bg-[#fffaf8] text-[#2d2430]"><SiteHeader />
<section className="relative overflow-hidden pt-28 sm:pt-32"><div className="pointer-events-none absolute -left-20 top-24 h-64 w-64 rounded-full bg-[#f8d7e6]/35 blur-3xl" /><div className="pointer-events-none absolute right-0 top-32 h-72 w-72 rounded-full bg-[#bee8ff]/30 blur-3xl" />
<div className="relative mx-auto grid max-w-7xl items-center gap-10 px-5 pb-16 lg:grid-cols-[0.9fr_1.1fr] lg:px-8 lg:pb-24"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#b78296]">Luniva Baby & Flowers</p><h1 className="mt-4 font-serif text-4xl font-semibold leading-[1.08] text-[#70528f] sm:text-5xl lg:text-6xl">En özel günleriniz için, sevgiyle hazırlanan hediyeler.</h1><p className="mt-5 max-w-lg text-base leading-7 text-[#5f535f]">Bebek doğumları, hastane ziyaretleri ve unutulmaz ilk karşılamalar için; çiçeklerin zarafetiyle kişiye özel detayları bir araya getiriyoruz.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/modeller" className="inline-flex items-center justify-center rounded-xl bg-[#7e62a6] px-5 py-3.5 text-xs font-bold uppercase tracking-[0.12em] text-white shadow-lg shadow-[#7e62a6]/20 transition hover:-translate-y-0.5 hover:bg-[#70528f]">Koleksiyonları keşfet</Link><a href={whatsappHref} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#c8b6ff]/70 bg-white px-5 py-3.5 text-xs font-bold uppercase tracking-[0.12em] text-[#70528f] transition hover:-translate-y-0.5"><WhatsAppIcon className="h-4 w-4" /> Bize yazın</a></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm font-medium text-[#786778]"><span>✦ Kişiye özel isim detayı</span><span>✦ Yumuşak pastel palet</span><span>✦ Özenli hediye sunumu</span></div></div>
<div className="grid grid-cols-[1.05fr_.95fr] gap-3 sm:gap-4"><div className="overflow-hidden rounded-[28px] bg-[#f1e9f2] shadow-xl shadow-[#8e7596]/15"><img src="/luniva/blue-swan-room-clean.png" alt="Luniva mavi kuğulu bebek aranjmanı" className="h-[390px] w-full object-cover sm:h-[500px]" /></div><div className="flex flex-col gap-3 sm:gap-4"><div className="overflow-hidden rounded-[28px] bg-[#f4edf2] shadow-lg shadow-[#8e7596]/10"><img src="/luniva/purple-swan-room-clean.png" alt="Luniva lila çiçekli bebek aranjmanı" className="h-[185px] w-full object-cover sm:h-[242px]" /></div><div className="rounded-[28px] bg-[#e9ddf0] p-6 text-[#70528f] sm:p-7"><p className="font-serif text-2xl leading-tight">Sizler ve bebeğiniz için tasarlandı.</p><p className="mt-3 text-sm leading-6 text-[#745f78]">Her ayrıntıda sevginizi hissettiren, fotoğraflara yakışan minik dokunuşlar.</p></div></div></div></div></section>
<section className="border-y border-[#eadfea] bg-white py-5"><div className="mx-auto grid max-w-6xl gap-4 px-5 text-center text-[11px] font-bold uppercase tracking-[0.14em] text-[#8a778a] sm:grid-cols-3"><span>Hayalinizi anlatın</span><span>Tasarımı birlikte netleştirelim</span><span>Özenle hazırlayıp teslim edelim</span></div></section>
<section className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-20"><div className="mb-9 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#b78296]">Koleksiyonlarımız</p><h2 className="mt-3 font-serif text-3xl font-semibold leading-tight text-[#70528f] sm:text-4xl">Her kutlama için nazik bir başlangıç.</h2></div><Link href="/modeller" className="text-sm font-bold text-[#8b6399] underline decoration-[#d5bfdf] underline-offset-4">Tüm modelleri inceleyin</Link></div><div className="grid gap-5 md:grid-cols-3">{collections.map((item) => <Link key={item.title} href={item.href} className="group overflow-hidden rounded-2xl border border-[#eadfea] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl hover:shadow-[#c8b6ff]/15"><div className="aspect-[4/4.2] overflow-hidden bg-[#f7eef5]"><img src={item.image} alt={item.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-5"><h3 className="font-serif text-xl font-semibold text-[#514153]">{item.title}</h3><p className="mt-2 text-sm leading-6 text-[#6d616d]">{item.text}</p><span className="mt-5 inline-block text-xs font-bold uppercase tracking-[0.12em] text-[#9d6780]">İncele →</span></div></Link>)}</div></section>
<section className="bg-[#f5eef7] py-16 lg:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#b78296]">Kişiye özel dokunuşlar</p><h2 className="mt-3 font-serif text-3xl font-semibold leading-tight text-[#70528f] sm:text-4xl">Minik mutluluklara, size ait bir imza.</h2><p className="mt-5 max-w-xl text-base leading-7 text-[#5f535f]">İsim, renk, çiçek seçimi ve notunuz… Hediye fikrinizi birlikte, bebeğinizin hikâyesine yakışan bir tasarıma dönüştürüyoruz.</p><Link href="/siparis" className="mt-7 inline-flex rounded-xl bg-white px-5 py-3.5 text-xs font-bold uppercase tracking-[0.12em] text-[#70528f] shadow-sm transition hover:-translate-y-0.5">Nasıl sipariş verilir?</Link></div><div className="overflow-hidden rounded-[28px] border border-white bg-white shadow-sm"><img src="/luniva/brand-variations-reference.png" alt="Luniva Baby marka logo varyasyonları" className="h-64 w-full object-cover object-[center_60%] sm:h-72" /></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-20"><div className="rounded-[28px] bg-[#70528f] px-6 py-10 text-center text-white sm:px-10 sm:py-14"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#f8d7e6]">Luniva ile</p><h2 className="mx-auto mt-3 max-w-2xl font-serif text-3xl font-semibold leading-tight sm:text-4xl">Güzel anılar, güzel bir hediyeyle başlar.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-white/80">Beğendiğiniz modeli gönderin; renk, isim ve teslimat ayrıntılarını WhatsApp üzerinden birlikte planlayalım.</p><a href={whatsappHref} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#25d366] px-5 py-3.5 text-xs font-bold uppercase tracking-[0.12em] text-white"><WhatsAppIcon className="h-4 w-4" /> Sipariş için WhatsApp</a></div></section><SiteFooter /><FloatingWhatsApp /></main>; }
