import Link from "next/link";
import { productCategories, productItems } from "../site-content";
import { FloatingWhatsApp } from "../components/FloatingWhatsApp";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";

export default function CategoriesPage() {
  return <main className="min-h-screen bg-[#fffaf8] text-[#2d2430]"><SiteHeader /><section className="mx-auto max-w-7xl px-5 pb-20 pt-32 lg:px-8"><p className="section-kicker text-xs font-bold uppercase text-[#b78296]">{"Luniva koleksiyonları"}</p><h1 className="mt-3 max-w-2xl font-serif text-4xl font-semibold leading-tight text-[#70528f] lg:text-5xl">{"En özel günleriniz için modeller"}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#655865]">{"Bebek doğumu, hastane ziyareti ve sevdiklerinize vereceğiniz hediyeler için modellere göz atın."}</p><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{productCategories.map((category) => { const count = productItems.filter((item) => item.categories.includes(category.slug)).length; return <Link key={category.slug} href={`/${category.slug}`} className="group overflow-hidden rounded-2xl border border-[#eadfea] bg-white shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-[#c8b6ff]/15"><div className="relative aspect-[4/3.2] overflow-hidden bg-[#f7eef5]"><img src={category.image} alt={category.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute left-3 top-3 rounded-full border border-[#e7cda6] bg-[#fff6ee] px-3 py-1 text-[11px] font-bold text-[#8f7044]">{count} model</span></div><div className="p-5"><h2 className="font-serif text-xl font-semibold text-[#514153]">{category.title}</h2><p className="mt-2 text-sm leading-6 text-[#6d616d]">{category.description}</p><span className="mt-5 inline-block text-xs font-bold uppercase tracking-[0.12em] text-[#9d6780]">{"Modelleri incele →"}</span></div></Link>; })}</div></section><SiteFooter /><FloatingWhatsApp /></main>;
}
